export const products = [
  {
    id: 'nuit-dambre',
    no: '01',
    name: 'Nuit d’Ambre',
    family: 'Amber · Oriental',
    notes: ['Saffron', 'Oud', 'Bourbon Vanilla'],
    price: 245,
    c1: '#f2b45c',
    c2: '#7e330d',
    desc: 'A slow-burning evening in amber light. Saffron threads flicker over smoked oud, settling into a warm, resinous vanilla that lingers until morning.',
    pyramid: { top: ['Saffron', 'Pink Pepper', 'Bergamot'], heart: ['Damask Rose', 'Labdanum'], base: ['Oud', 'Bourbon Vanilla', 'Ambergris'] },
  },
  {
    id: 'rose-eternelle',
    no: '02',
    name: 'Rose Éternelle',
    family: 'Floral · Chypre',
    notes: ['Damask Rose', 'Lychee', 'White Musk'],
    price: 225,
    c1: '#f59fb0',
    c2: '#86203f',
    desc: 'A rose picked at dawn and kept forever. Dewy lychee opens onto a velvet heart of Damask petals, resting on clean white musk and moss.',
    pyramid: { top: ['Lychee', 'Pink Grapefruit'], heart: ['Damask Rose', 'Peony', 'Geranium'], base: ['White Musk', 'Oakmoss', 'Patchouli'] },
  },
  {
    id: 'vetiver-noir',
    no: '03',
    name: 'Vétiver Noir',
    family: 'Woody · Smoky',
    notes: ['Haitian Vetiver', 'Black Pepper', 'Birch Tar'],
    price: 235,
    c1: '#9fb286',
    c2: '#1c2717',
    desc: 'Earth after a storm. Crackling black pepper and smoked birch give way to a dense, rooty vetiver with the texture of wet stone.',
    pyramid: { top: ['Black Pepper', 'Grapefruit'], heart: ['Haitian Vetiver', 'Cypress'], base: ['Birch Tar', 'Cedar', 'Leather'] },
  },
  {
    id: 'iris-lumiere',
    no: '04',
    name: 'Iris Lumière',
    family: 'Powdery · Floral',
    notes: ['Orris Butter', 'Violet Leaf', 'Suede'],
    price: 290,
    c1: '#cfc0f4',
    c2: '#4a3887',
    desc: 'Light through a silk curtain. Precious orris butter, aged three years, is softened by violet leaf and a whisper of warm suede.',
    pyramid: { top: ['Violet Leaf', 'Aldehydes'], heart: ['Orris Butter', 'Mimosa'], base: ['Suede', 'Tonka', 'Sandalwood'] },
  },
  {
    id: 'fleur-de-sel',
    no: '05',
    name: 'Fleur de Sel',
    family: 'Aquatic · Citrus',
    notes: ['Sea Salt', 'Neroli', 'Driftwood'],
    price: 195,
    c1: '#b0e4ec',
    c2: '#1b5a70',
    desc: 'Skin warmed by a Breton sun. Crystalline sea salt and bright neroli drift over sun-bleached driftwood and ambrette seed.',
    pyramid: { top: ['Sea Salt', 'Lemon Zest'], heart: ['Neroli', 'Rosemary'], base: ['Driftwood', 'Ambrette', 'Musk'] },
  },
  {
    id: 'or-blanc',
    no: '06',
    name: 'Or Blanc',
    family: 'Musky · Tea',
    notes: ['White Tea', 'Pear', 'Cashmere'],
    price: 210,
    c1: '#fff0cc',
    c2: '#ad8e4e',
    desc: 'The quiet luxury of clean linen. Silver-needle white tea and juicy pear rest on a soft, skin-like accord of cashmere woods.',
    pyramid: { top: ['Pear', 'Mandarin'], heart: ['White Tea', 'Jasmine Sambac'], base: ['Cashmere Woods', 'Musk'] },
  },
];

export const projects = [
  { title: 'Solstice', kind: 'Film campaign', year: '2026', c1: '#f2b45c', c2: '#3a1606', variant: 1 },
  { title: 'The Glass Garden', kind: 'Installation · Milan', year: '2025', c1: '#b0e4ec', c2: '#0f2c38', variant: 2 },
  { title: 'Nocturne Edition', kind: 'Limited bottle design', year: '2025', c1: '#cfc0f4', c2: '#1d1538', variant: 3 },
  { title: 'Maison Saint-Honoré', kind: 'Flagship architecture', year: '2024', c1: '#fff0cc', c2: '#3b2f18', variant: 1 },
  { title: 'Les Heures', kind: 'Editorial & print', year: '2024', c1: '#f59fb0', c2: '#3a0c1a', variant: 2 },
  { title: 'Atelier Ouvert', kind: 'Experiential launch', year: '2023', c1: '#9fb286', c2: '#111a0d', variant: 3 },
];
